#!/bin/bash
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

ynh_backup "$install_dir"
ynh_backup "$data_dir"

ynh_print_info "Backup script completed for $app."
