#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression "Stopping $app service..."
ynh_systemd_action --service_name="$app" --action="stop"
yunohost service remove "$app"
ynh_remove_systemd_config

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing nginx configuration..."
ynh_remove_nginx_config

#=================================================
# REMOVE NODE.JS
#=================================================
ynh_script_progression "Removing Node.js..."
ynh_remove_nodejs

#=================================================
# REMOVE APP FILES
#=================================================
ynh_script_progression "Removing application files..."
ynh_secure_remove "$install_dir"
ynh_secure_remove "$data_dir"

ynh_script_progression "Removal of $app completed"
